Rework hash formats and add JSON format
amazing-print/amazing_print pull request #83
Opened 2021-10-07 03:57 UTC by HarlemSquirrel

Closes #70
Closes #47

This is going to require a major version bump.

Test object

```rb
{ a: 'cheese', 'a' => 'burger', 1 => 'fries',  1.0 => 'version', count: 33, time: Time.now, nothing: nil, list: [1, 'a', :sym, Time.now, nil], nested_hash: { hi: 'there' }, :"first_name(fn)" => "Al" }
```

![image](https://github.com/user-attachments/assets/cbaebf69-0a98-4bbe-8cb9-778f56205fbf)

![image](https://github.com/user-attachments/assets/7317257b-4751-44ac-8b54-9d3b3cf26632)

2024-03-15 02:47 UTC, HarlemSquirrel commented
Should we also support the JSON format for arrays? I guess the only thing it would do is convert symbols to strings inside the array which doesn't seem particularly helpful but also feels a bit incomplete without it if we're doing that in hashes.

2025-05-19 10:51 UTC, paddor requested changes

2025-05-19 10:51 UTC, paddor commented on lib/amazing_print/json_helper.rb
> +      elsif is_key && %w[BigDecimal Float Integer].include?(object.class.name)
Why compare the `Class#name` instead of the `Class` objects themselves? Also, maybe these two arrays here should be put into constants in this module.

2025-05-22 00:36 UTC, HarlemSquirrel commented on lib/amazing_print/json_helper.rb
> +      elsif is_key && %w[BigDecimal Float Integer].include?(object.class.name)
Yeah let me try that

2025-05-22 00:46 UTC, HarlemSquirrel commented on lib/amazing_print/json_helper.rb
> +      elsif is_key && %w[BigDecimal Float Integer].include?(object.class.name)
Ah yeah the reason is that `BigDecimal` may not already be required and I don't think we should require objects just for this

2025-05-22 00:48 UTC, HarlemSquirrel commented on lib/amazing_print/json_helper.rb
> +      elsif is_key && %w[BigDecimal Float Integer].include?(object.class.name)
Updated

2025-05-22 04:49 UTC, paddor approved these changes

2025-05-22 14:23 UTC, merged